[workspace]
resolver = "2"
members = ["crates/*", "apps/*"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 1

[patch.crates-io]
microfft = { git = "https://gitlab.com/teskje/microfft-rs.git", rev = "f783b1effe66a24984f46b3fccca00d18fda5970" }
eframe = { git = "https://github.com/emilk/egui", rev = "c19a7ff34f162ee7162de0b11277de42415991ff" }
