[workspace]
members = ["loid", "cli", "common"]

[profile.dev]
opt-level = 2

[profile.release]
debug = 1
lto = "thin"

[patch.crates-io]
microfft = { git = "https://gitlab.com/teskje/microfft-rs.git", rev = "f783b1effe66a24984f46b3fccca00d18fda5970" }
