[package]
name = "speaky"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.16.0"
microfft = "0.4.0"
num-complex = "0.4.0"
rodio = "0.15.0"
# spectrum-analyzer = "1.2.3"
ttspico = "0.1.5"

[features]
