[package]
name = "spectrum"
version = "0.0.0"
edition = "2021"

publish = false
license = "MPL-2.0"

[dependencies]
microfft = { version = "0.4.0", features = ["size-16384"] }
num-complex = "0.4.0"
paste = "1.0.6"
audio = { path = "../audio" }
