[package]
name = "tts"
version = "0.0.0"
edition = "2021"

publish = false
license = "MPL-2.0"

[dependencies]
ttspico = "0.1.5"
color-eyre = "0.6.0"          # TODO: better error handling
tracing = "0.1.31"
audio = { path = "../audio", features = ["cpal"] }
