on: [push, pull_request]

name: CI

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Security audit
              uses: actions-rs/audit-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

    check:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Install eframe dependencies
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev

            - name: Install cpal Dependencies
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt install libasound2-dev

            - name: Stable Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
            - uses: actions/checkout@v2
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --all-features --all-targets

    # Clippy on web?
    clippy:
        needs: check
        runs-on: ubuntu-latest
        steps:
            - name: Install eframe dependencies
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev

            - name: Install cpal Dependencies
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt install libasound2-dev

            - name: Stable Rust with clippy
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  components: clippy
            - uses: actions/checkout@v2
            - name: Annotate commit with clippy warnings
              uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features --all-targets

    fmt:
        runs-on: ubuntu-latest
        steps:
            - name: Stable Rust with rustfmt
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  components: rustfmt
            - uses: actions/checkout@v2
            - name: Check formatting
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --check

    deploy-loid:
        needs: check
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        env:
            TRUNK_VERSION: "v0.14.0"
        steps:
            - name: Stable Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
            - uses: actions/checkout@v2
            - name: Install trunk
              working-directory: loid
              run: wget -qO- "https://github.com/thedodd/trunk/releases/download/${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz" | tar -xzf-
            - name: Build Loid
              working-directory: loid
              run: trunk build --release
            - name: Deploy Loid
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: dist-loid
                  folder: loid/dist
